### ISSUE TITLE
Feature Request - Move source code into a src directory

### ISSUE THREAD

**Issue by CreepPork** [TITAN-Contractors/TITAN-Robotics#6]
This is a good convention and allows other people to understand your main pieces of the code.
E.g.
- index.js -> src/index.js
- commands/* -> src/commands/*

**Comment by SDTheCyanWyan** [comment]
Shifted and categorised

**Comment by CreepPork** [comment]
Not fixed.

https://github.com/TITAN-Contractors/TITAN-Robotics/blob/15cd72424e497c9ec8585f71fb01198a7b3562ec/package.json#L5

Should be updated to reflect the changes.

**Comment by SDTheCyanWyan** [comment]
Fixed, much appreciated.
