### ISSUE TITLE
License is an invalid format for npm

### ISSUE THREAD

**Issue by CreepPork** [TITAN-Contractors/TITAN-Robotics#9]
https://github.com/TITAN-Contractors/TITAN-Robotics/blob/56ee05843794e27b71a1f04910c48c4850abe484/package.json#L14

**Comment by SDTheCyanWyan** [comment]
When setting up the package, `license` was asked to be entered. Could not enter the License that the project is utilising. 

What would be the correct format?

**Comment by CreepPork** [comment]
NPM uses SPDX's list of software licenses. The list is available here: https://spdx.org/licenses/. You should use the identifier field.

**Comment by SDTheCyanWyan** [comment]
Fixed, thanks.
